<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Certificate;

class CertificateSeeder extends Seeder
{
    public function run(): void
    {
        $certificates = [
            [
                'title' => 'Medium and High-Pressure Oil-Injected Screw Compressor Unit Circulating Oil Circuit Control System',
                'description' => 'Patent certificate for the oil circuit control system of a medium and high-pressure oil-injected screw compressor unit.',
                'image' => 'certificates/01.jpg',
                'certificate_number' => 'ZL 2010 1 0152926.4',
                'issue_date' => '2010-04-22',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 1,
            ],
            [
                'title' => 'Diesel Engine Governor for Mobile Screw Compressor',
                'description' => 'Patent certificate for a diesel engine speed governor used in mobile screw compressors.',
                'image' => 'certificates/02.jpg',
                'certificate_number' => 'ZL 2010 1 0276865.2',
                'issue_date' => '2010-09-09',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 2,
            ],
            [
                'title' => 'Micro Heat Regenerative Adsorption Dryer Controlled by Multi-Channel Switching Valve',
                'description' => 'Patent certificate for a micro heat regenerative adsorption dryer with multi-channel switching valve control.',
                'image' => 'certificates/03.jpg',
                'certificate_number' => 'ZL 2011 1 0383895.8',
                'issue_date' => '2011-11-28',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 3,
            ],
            [
                'title' => 'Lubricating Oil Pressure Energy Recovery System for Oil-Injected Screw Compressors',
                'description' => 'Patent certificate for an energy recovery system utilizing lubricating oil pressure in oil-injected screw compressors.',
                'image' => 'certificates/04.jpg',
                'certificate_number' => 'ZL 2012 1 0518360.1',
                'issue_date' => '2012-12-06',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 4,
            ],
            [
                'title' => 'Thermal Pipeline Expansion Joint Structure',
                'description' => 'Patent certificate for an expansion joint structure used in thermal pipelines.',
                'image' => 'certificates/05.jpg',
                'certificate_number' => 'ZL 2012 1 0537976.3',
                'issue_date' => '2012-12-13',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 5,
            ],
            [
                'title' => 'Diesel Engine Exhaust Expansion Joint Structure',
                'description' => 'Patent certificate for an expansion joint structure for diesel engine exhaust systems.',
                'image' => 'certificates/06.jpg',
                'certificate_number' => 'ZL 2012 1 0538264.3',
                'issue_date' => '2012-12-13',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 6,
            ],
            [
                'title' => 'Automatic Power Transmission Control System for Vehicle-Mounted Compressor',
                'description' => 'Patent certificate for an automatic control system for power transmission in vehicle-mounted compressors.',
                'image' => 'certificates/07.jpg',
                'certificate_number' => 'ZL 2014 1 0412767.5',
                'issue_date' => '2014-08-21',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 7,
            ],
            [
                'title' => 'Oil Circuit System for Air-Cooled Dry Screw Compressor',
                'description' => 'Patent certificate for the oil circuit system of an air-cooled dry screw compressor.',
                'image' => 'certificates/08.jpg',
                'certificate_number' => 'ZL 2015 1 0391413.1',
                'issue_date' => '2015-07-07',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 8,
            ],
            [
                'title' => 'Design Method for Screw End Profile with Tooth Surface Clearance',
                'description' => 'Patent certificate for a design method of screw end profile containing tooth surface clearance.',
                'image' => 'certificates/09.jpg',
                'certificate_number' => 'ZL 2015 1 0391414.6',
                'issue_date' => '2015-07-07',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 9,
            ],
            [
                'title' => 'Oil Injection and Gas Compensation Structure for Oil-Injected Screw Vacuum Pump',
                'description' => 'Patent certificate for an oil injection and gas compensation structure in oil-injected screw vacuum pumps.',
                'image' => 'certificates/10.jpg',
                'certificate_number' => 'ZL 2015 1 0391451.7',
                'issue_date' => '2015-07-07',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 10,
            ],
            [
                'title' => 'Design Method for Twin Screw End Profiles',
                'description' => 'Patent certificate for the design method of twin screw end profiles.',
                'image' => 'certificates/11.jpg',
                'certificate_number' => 'ZL 2015 1 0565128.7',
                'issue_date' => '2015-09-08',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 11,
            ],
            [
                'title' => 'Cooling Control System for Air-Cooled Screw Compressor',
                'description' => 'Patent certificate for a cooling control system used in air-cooled screw compressors.',
                'image' => 'certificates/12.jpg',
                'certificate_number' => 'ZL 2015 1 0565196.3',
                'issue_date' => '2015-09-08',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 12,
            ],
            [
                'title' => 'Oil-Gas Separation System for Oil-Injected Screw Vacuum Pump',
                'description' => 'Patent certificate for an oil-gas separation system designed for oil-injected screw vacuum pumps.',
                'image' => 'certificates/13.jpg',
                'certificate_number' => 'ZL 2015 1 0565241.5',
                'issue_date' => '2015-09-08',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 13,
            ],
            [
                'title' => 'Vacuum Regulating Valve Device for Positive Displacement Vacuum Pump',
                'description' => 'Patent certificate for a vacuum regulating valve device used in positive displacement vacuum pumps.',
                'image' => 'certificates/14.jpg',
                'certificate_number' => 'ZL 2015 1 0950796.1',
                'issue_date' => '2015-12-19',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 14,
            ],
            [
                'title' => 'Screw Compressor System with Organic Rankine Cycle',
                'description' => 'Utility model patent for a screw compressor system integrated with an Organic Rankine Cycle.',
                'image' => 'certificates/15.jpg',
                'certificate_number' => 'ZL 2015 2 0834335.3',
                'issue_date' => '2015-10-27',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 15,
            ],
            [
                'title' => 'Oil Return Structure at Exhaust End of Oil-Injected Screw Compressor',
                'description' => 'Utility model patent for an oil return structure at the exhaust end of an oil-injected screw compressor.',
                'image' => 'certificates/16.jpg',
                'certificate_number' => 'ZL 2015 2 0846095.9',
                'issue_date' => '2015-10-29',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 16,
            ],
            [
                'title' => 'Pressure Control System for Aircraft Air Source Vehicle',
                'description' => 'Patent certificate for a pressure control system for aircraft air source vehicles.',
                'image' => 'certificates/17.jpg',
                'certificate_number' => 'ZL 2016 1 0571627.1',
                'issue_date' => '2016-07-20',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 17,
            ],
            [
                'title' => 'Manufacturing Process for Screw Compressor Housing',
                'description' => 'Patent certificate for the manufacturing process of screw compressor housings.',
                'image' => 'certificates/18.jpg',
                'certificate_number' => 'ZL 2017 1 1249141.7',
                'issue_date' => '2017-12-01',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 18,
            ],
            [
                'title' => 'End Cover Structure for Oil-Gas Separator',
                'description' => 'Utility model patent for an end cover structure of an oil-gas separator.',
                'image' => 'certificates/19.jpg',
                'certificate_number' => 'ZL 2017 2 0686217.1',
                'issue_date' => '2017-06-14',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 19,
            ],
            [
                'title' => 'Tool for Accurately Determining the Shape of Screw Grinding Wheel',
                'description' => 'Utility model patent for a tool used to accurately determine the shape of a screw grinding wheel.',
                'image' => 'certificates/20.jpg',
                'certificate_number' => 'ZL 2017 2 0810178.1',
                'issue_date' => '2017-07-06',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 20,
            ],
            [
                'title' => 'Loading and Unloading System for Oil-Injected Screw Compressor',
                'description' => 'Utility model patent for a loading and unloading system used in oil-injected screw compressors.',
                'image' => 'certificates/21.jpg',
                'certificate_number' => 'ZL 2017 2 0929176.4',
                'issue_date' => '2017-07-28',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 21,
            ],
            [
                'title' => 'Air Intake Regulating Valve Structure',
                'description' => 'Utility model patent for an air intake regulating valve structure.',
                'image' => 'certificates/22.jpg',
                'certificate_number' => 'ZL 2017 2 0929177.9',
                'issue_date' => '2017-07-28',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 22,
            ],
            [
                'title' => 'Oil Return Throttle Valve Structure for Oil-Injected Screw Compressor',
                'description' => 'Utility model patent for an oil return throttle valve structure used in oil-injected screw compressors.',
                'image' => 'certificates/23.jpg',
                'certificate_number' => 'ZL 2017 2 0929674.9',
                'issue_date' => '2017-07-28',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 23,
            ],
            [
                'title' => 'Oil Injection Temperature Adjustment Structure for Oil-Injected Screw Compressor',
                'description' => 'Utility model patent for an oil injection temperature regulation structure used in oil-injected screw compressors.',
                'image' => 'certificates/24.jpg',
                'certificate_number' => 'ZL 2017 2 0962064.9',
                'issue_date' => '2017-08-03',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 24,
            ],
            [
                'title' => 'Two-Stage Screw Expander Structure for Waste Heat Recovery from High-Power Diesel Engines',
                'description' => 'Utility model patent for a two-stage screw expander structure used for waste heat recovery from high-power diesel engines.',
                'image' => 'certificates/25.jpg',
                'certificate_number' => 'ZL 2017 2 1023415.6',
                'issue_date' => '2017-08-16',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 25,
            ],
            [
                'title' => 'Aftercooler Structure for Dry Screw Air Compressor',
                'description' => 'Utility model patent for an aftercooler structure used in dry screw air compressors.',
                'image' => 'certificates/26.jpg',
                'certificate_number' => 'ZL 2017 2 1023440.4',
                'issue_date' => '2017-08-16',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 26,
            ],
            [
                'title' => 'Screw Compressor Pin Extractor',
                'description' => 'Utility model patent for a pin extractor tool used in screw compressors.',
                'image' => 'certificates/27.jpg',
                'certificate_number' => 'ZL 2017 2 1023461.6',
                'issue_date' => '2017-08-16',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 27,
            ],
            [
                'title' => 'Framework Oil Seal Installation Structure',
                'description' => 'Utility model patent for a framework oil seal installation structure.',
                'image' => 'certificates/28.jpg',
                'certificate_number' => 'ZL 2017 2 1023462.0',
                'issue_date' => '2017-08-16',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 28,
            ],
            [
                'title' => 'Fixture for Machining and Fixing Screw Compressor Housing Parts',
                'description' => 'Utility model patent for a fixture used for machining and fixing screw compressor housing components.',
                'image' => 'certificates/29.jpg',
                'certificate_number' => 'ZL 2017 2 1023463.5',
                'issue_date' => '2017-08-16',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 29,
            ],
            [
                'title' => 'Interstage Heating Structure for Two-Stage Screw Expander',
                'description' => 'Utility model patent for an interstage heating structure used in two-stage screw expanders.',
                'image' => 'certificates/30.jpg',
                'certificate_number' => 'ZL 2017 2 1023466.9',
                'issue_date' => '2017-08-16',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration',
                'status' => true,
                'order' => 30,
            ],
            [
                'order' => 31,
                'title' => 'Performance Testing Platform for Radial Thrust Sliding Bearings in Water-Lubricated Sliding Presses',
                'description' => 'Utility model patent for a performance testing platform designed for radial thrust sliding bearings in water-lubricated sliding presses.',
                'image' => 'certificates/31.jpg',
                'certificate_number' => 'ZL 2017 2 1023508.9',
                'issue_date' => '2017-08-16',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
            ],
            [
                'order' => 32,
                'title' => 'Volume Flow Adjustment Structure for Screw Compressors',
                'description' => 'Utility model patent for a structure that adjusts the volume flow in screw compressors.',
                'image' => 'certificates/32.jpg',
                'certificate_number' => 'ZL 2017 2 1397074.9',
                'issue_date' => '2017-10-27',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
            ],
            [
                'order' => 33,
                'title' => 'Speed Control System for Diesel Mobile Screw Compressors',
                'description' => 'Utility model patent for a speed control system designed for diesel-powered mobile screw compressors.',
                'image' => 'certificates/33.jpg',
                'certificate_number' => 'ZL 2017 2 1647308.0',
                'issue_date' => '2017-12-01',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
            ],
            [
                'order' => 34,
                'title' => 'Integrated Oil Circuit Structure for Dry Screw Compressors',
                'description' => 'Utility model patent for an integrated oil circuit structure in dry screw compressors.',
                'image' => 'certificates/34.jpg',
                'certificate_number' => 'ZL 2017 2 1683399.3',
                'issue_date' => '2017-12-07',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
            ],
            [
                'order' => 35,
                'title' => 'Appearance Design of Oil-Injected Screw Compressor',
                'description' => 'Design patent for the external appearance of an oil-injected screw compressor.',
                'image' => 'certificates/35.jpg',
                'certificate_number' => 'ZL 2017 3 0239251.X',
                'issue_date' => '2017-06-13',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
            ],
            [
                'order' => 36,
                'title' => 'Appearance Design of Oil-Injected Screw Compressor Housing (2)',
                'description' => 'Design patent for the external housing of an oil-injected screw compressor (version 2).',
                'image' => 'certificates/36.jpg',
                'certificate_number' => 'ZL 2017 3 0261718.0',
                'issue_date' => '2017-06-22',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
            ],
            [
                'order' => 37,
                'title' => 'Automatic Water Replenishment System for Oil-Injected Screw Air Compressors',
                'description' => 'Utility model patent for an automatic water replenishment system in oil-injected screw air compressors.',
                'image' => 'certificates/37.jpg',
                'certificate_number' => 'ZL 2018 2 0042963.1',
                'issue_date' => '2018-01-11',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
            ],
            [
                'order' => 38,
                'title' => 'Integrated System of Screw Expander, Screw Compressor, and Motor',
                'description' => 'Utility model patent for an integrated system combining a screw expander, screw compressor, and motor.',
                'image' => 'certificates/38.jpg',
                'certificate_number' => 'ZL 2018 2 0071196.7',
                'issue_date' => '2018-01-17',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
            ],
            [
                'title' => 'Bearing Installation Device',
                'description' => 'Utility model patent for a specialized bearing installation device.',
                'image' => 'certificates/43.jpg',
                'certificate_number' => 'ZL 2019 2 1767782.6',
                'issue_date' => '2019-10-23',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
                'order' => 43,
            ],
            [
                'title' => 'IoT Gas Flow Regulation and Control Circuit for Multiple Air Compressor Units',
                'description' => 'Utility model patent for an IoT-based control circuit to regulate gas flow in multiple air compressor units.',
                'image' => 'certificates/46.jpg',
                'certificate_number' => 'ZL 2020 2 0106067.4',
                'issue_date' => '2020-01-10',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
                'order' => 46,
            ],
            [
                'title' => 'Capacity Adjustment Slide Valve Structure for Screw Compressors',
                'description' => 'Utility model patent for a capacity adjustment slide valve structure used in screw compressors.',
                'image' => 'certificates/47.jpg',
                'certificate_number' => 'ZL 2020 2 0113294.X',
                'issue_date' => '2020-01-13',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
                'order' => 47,
            ],
            [
                'title' => 'Lubricating Oil Distribution System for Air Compressors',
                'description' => 'Utility model patent for a lubricating oil distribution system used in air compressors.',
                'image' => 'certificates/48.jpg',
                'certificate_number' => 'ZL 2020 2 1241746.9',
                'issue_date' => '2020-06-30',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
                'order' => 48,
            ],
            [
                'title' => 'Oil-Free Screw Gas Conveying Device',
                'description' => 'Utility model patent for an oil-free screw gas conveying device.',
                'image' => 'certificates/49.jpg',
                'certificate_number' => 'ZL 2020 2 1241747.3',
                'issue_date' => '2020-06-30',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
                'order' => 49,
            ],
            [
                'title' => 'Performance Testing System for Screw Air Compressor Main Units',
                'description' => 'Utility model patent for a performance testing system for screw air compressor main units.',
                'image' => 'certificates/50.jpg',
                'certificate_number' => 'ZL 2020 2 1241770.2',
                'issue_date' => '2020-06-30',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
                'order' => 50,
            ],
            [
                'title' => 'Air Intake Regulating Valve Structure',
                'description' => 'Invention patent for a structure of air intake regulating valve.',
                'image' => 'certificates/61.jpg',
                'certificate_number' => 'ZL 2017 1 0630728.6',
                'issue_date' => '2024-05-10',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
                'order' => 61,
            ],
            [
                'title' => 'Performance Testing Platform for Radial Thrust Sliding Bearings in Water-Lubricated Sliding Presses',
                'description' => 'Invention patent for a performance testing platform for radial thrust sliding bearings in water-lubricated sliding presses.',
                'image' => 'certificates/63.jpg',
                'certificate_number' => 'ZL 2017 1 0700519.4',
                'issue_date' => '2023-08-29',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
                'order' => 63,
            ],
            [
                'title' => 'Waste Heat Recovery Oil-Injected Screw Compressor Control System and Control Method',
                'description' => 'Invention patent for a control system and control method for waste heat recovery oil-injected screw compressors.',
                'image' => 'certificates/64.jpg',
                'certificate_number' => 'ZL 2019 1 0690257.7',
                'issue_date' => '2024-08-27',
                'expiry_date' => null,
                'issuing_authority' => 'China National Intellectual Property Administration (CNIPA)',
                'status' => true,
                'order' => 64,
            ],
        ];

        foreach ($certificates as $certificate) {
            Certificate::create($certificate);
        }
    }
}
