<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AFG', 'flag' => '🇦🇫', 'phone_code' => '+93'],
            ['name' => 'Albania', 'code' => 'ALB', 'flag' => '🇦🇱', 'phone_code' => '+355'],
            ['name' => 'Algeria', 'code' => 'DZA', 'flag' => '🇩🇿', 'phone_code' => '+213'],
            ['name' => 'American Samoa', 'code' => 'ASM', 'flag' => '🇦🇸', 'phone_code' => '+1684'],
            ['name' => 'Andorra', 'code' => 'AND', 'flag' => '🇦🇩', 'phone_code' => '+376'],
            ['name' => 'Angola', 'code' => 'AGO', 'flag' => '🇦🇴', 'phone_code' => '+244'],
            ['name' => 'Anguilla', 'code' => 'AIA', 'flag' => '🇦🇮', 'phone_code' => '+1264'],
            ['name' => 'Antarctica', 'code' => 'ANA', 'flag' => '', 'phone_code' => '+672'],
            ['name' => 'Antigua and Barbuda', 'code' => 'ATG', 'flag' => '🇦🇬', 'phone_code' => '+1268'],
            ['name' => 'Argentina', 'code' => 'ARG', 'flag' => '🇦🇷', 'phone_code' => '+54'],
            ['name' => 'Armenia', 'code' => 'ARM', 'flag' => '🇦🇲', 'phone_code' => '+374'],
            ['name' => 'Aruba', 'code' => 'ABW', 'flag' => '🇦🇼', 'phone_code' => '+297'],
            ['name' => 'Australia', 'code' => 'AUS', 'flag' => '🇦🇺', 'phone_code' => '+61'],
            ['name' => 'Austria', 'code' => 'AUT', 'flag' => '🇦🇹', 'phone_code' => '+43'],
            ['name' => 'Azerbaijan', 'code' => 'AZE', 'flag' => '🇦🇿', 'phone_code' => '+994'],
            ['name' => 'Bahamas', 'code' => 'BHS', 'flag' => '🇧🇸', 'phone_code' => '+1242'],
            ['name' => 'Bahrain', 'code' => 'BHR', 'flag' => '🇧🇭', 'phone_code' => '+973'],
            ['name' => 'Bangladesh', 'code' => 'BGD', 'flag' => '🇧🇩', 'phone_code' => '+880'],
            ['name' => 'Barbados', 'code' => 'BRB', 'flag' => '🇧🇧', 'phone_code' => '+1246'],
            ['name' => 'Belarus', 'code' => 'BLR', 'flag' => '🇧🇾', 'phone_code' => '+375'],
            ['name' => 'Belgium', 'code' => 'BEL', 'flag' => '🇧🇪', 'phone_code' => '+32'],
            ['name' => 'Belize', 'code' => 'BLZ', 'flag' => '🇧🇿', 'phone_code' => '+501'],
            ['name' => 'Benin', 'code' => 'BEN', 'flag' => '🇧🇯', 'phone_code' => '+229'],
            ['name' => 'Bermuda', 'code' => 'BMU', 'flag' => '🇧🇲', 'phone_code' => '+1441'],
            ['name' => 'Bhutan', 'code' => 'BTN', 'flag' => '🇧🇹', 'phone_code' => '+975'],
            ['name' => 'Bolivia', 'code' => 'BOL', 'flag' => '🇧🇴', 'phone_code' => '+591'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BIH', 'flag' => '🇧🇦', 'phone_code' => '+387'],
            ['name' => 'Botswana', 'code' => 'BWA', 'flag' => '🇧🇼', 'phone_code' => '+267'],
            ['name' => 'Bouvet Island', 'code' => 'BV', 'flag' => '', 'phone_code' => '+55'],
            ['name' => 'Brazil', 'code' => 'BRA', 'flag' => '🇧🇷', 'phone_code' => '+55'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IOT', 'flag' => '', 'phone_code' => '+246'],
            ['name' => 'Brunei Darussalam', 'code' => 'BRN', 'flag' => '🇧🇳', 'phone_code' => '+673'],
            ['name' => 'Bulgaria', 'code' => 'BGR', 'flag' => '🇧🇬', 'phone_code' => '+359'],
            ['name' => 'Burkina Faso', 'code' => 'BFA', 'flag' => '🇧🇫', 'phone_code' => '+226'],
            ['name' => 'Burundi', 'code' => 'BDI', 'flag' => '🇧🇮', 'phone_code' => '+257'],
            ['name' => 'Cambodia', 'code' => 'KHM', 'flag' => '🇰🇭', 'phone_code' => '+855'],
            ['name' => 'Cameroon', 'code' => 'CMR', 'flag' => '🇨🇲', 'phone_code' => '+237'],
            ['name' => 'Canada', 'code' => 'CAN', 'flag' => '🇨🇦', 'phone_code' => '+1'],
            ['name' => 'Cape Verde', 'code' => 'CPV', 'flag' => '🇨🇻', 'phone_code' => '+238'],
            ['name' => 'Cayman Islands', 'code' => 'CYM', 'flag' => '🇰🇾', 'phone_code' => '+1345'],
            ['name' => 'Central African Republic', 'code' => 'CAF', 'flag' => '🇨🇫', 'phone_code' => '+236'],
            ['name' => 'Chad', 'code' => 'TCD', 'flag' => '🇹🇩', 'phone_code' => '+235'],
            ['name' => 'Chile', 'code' => 'CHL', 'flag' => '🇨🇱', 'phone_code' => '+56'],
            ['name' => 'China', 'code' => 'CHN', 'flag' => '🇨🇳', 'phone_code' => '+86'],
            ['name' => 'Christmas Island', 'code' => 'CX', 'flag' => '', 'phone_code' => '+61'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'flag' => '', 'phone_code' => '+61'],
            ['name' => 'Colombia', 'code' => 'COL', 'flag' => '🇨🇴', 'phone_code' => '+57'],
            ['name' => 'Comoros', 'code' => 'COM', 'flag' => '🇰🇲', 'phone_code' => '+269'],
            ['name' => 'Congo', 'code' => 'COG', 'flag' => '🇨🇬', 'phone_code' => '+242'],
            ['name' => 'Congo, the Democratic Republic of the', 'code' => 'COD', 'flag' => '🇨🇩', 'phone_code' => '+243'],
            ['name' => 'Cook Islands', 'code' => 'COK', 'flag' => '🇨🇰', 'phone_code' => '+682'],
            ['name' => 'Costa Rica', 'code' => 'CRI', 'flag' => '🇨🇷', 'phone_code' => '+506'],
            ['name' => 'Cote D\'Ivoire', 'code' => 'CIV', 'flag' => '🇨🇮', 'phone_code' => '+225'],
            ['name' => 'Croatia', 'code' => 'HRV', 'flag' => '🇭🇷', 'phone_code' => '+385'],
            ['name' => 'Cuba', 'code' => 'CUB', 'flag' => '🇨🇺', 'phone_code' => '+53'],
            ['name' => 'Cyprus', 'code' => 'CYP', 'flag' => '🇨🇾', 'phone_code' => '+357'],
            ['name' => 'Czech Republic', 'code' => 'CZE', 'flag' => '🇨🇿', 'phone_code' => '+420'],
            ['name' => 'Denmark', 'code' => 'DNK', 'flag' => '🇩🇰', 'phone_code' => '+45'],
            ['name' => 'Djibouti', 'code' => 'DJI', 'flag' => '🇩🇯', 'phone_code' => '+253'],
            ['name' => 'Dominica', 'code' => 'DMA', 'flag' => '🇩🇲', 'phone_code' => '+1767'],
            ['name' => 'Dominican Republic', 'code' => 'DOM', 'flag' => '🇩🇴', 'phone_code' => '+1809'],
            ['name' => 'Ecuador', 'code' => 'ECU', 'flag' => '🇪🇨', 'phone_code' => '+593'],
            ['name' => 'Egypt', 'code' => 'EGY', 'flag' => '🇪🇬', 'phone_code' => '+20'],
            ['name' => 'El Salvador', 'code' => 'SLV', 'flag' => '🇸🇻', 'phone_code' => '+503'],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ', 'flag' => '🇬🇶', 'phone_code' => '+240'],
            ['name' => 'Eritrea', 'code' => 'ERI', 'flag' => '🇪🇷', 'phone_code' => '+291'],
            ['name' => 'Estonia', 'code' => 'EST', 'flag' => '🇪🇪', 'phone_code' => '+372'],
            ['name' => 'Ethiopia', 'code' => 'ETH', 'flag' => '🇪🇹', 'phone_code' => '+251'],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FLK', 'flag' => '🇫🇰', 'phone_code' => '+500'],
            ['name' => 'Faroe Islands', 'code' => 'FRO', 'flag' => '🇫🇴', 'phone_code' => '+298'],
            ['name' => 'Fiji', 'code' => 'FJI', 'flag' => '🇫🇯', 'phone_code' => '+679'],
            ['name' => 'Finland', 'code' => 'FIN', 'flag' => '🇫🇮', 'phone_code' => '+358'],
            ['name' => 'France', 'code' => 'FRA', 'flag' => '🇫🇷', 'phone_code' => '+33'],
            ['name' => 'French Guiana', 'code' => 'GUF', 'flag' => '🇬🇫', 'phone_code' => '+594'],
            ['name' => 'French Polynesia', 'code' => 'PYF', 'flag' => '🇵🇫', 'phone_code' => '+689'],
            ['name' => 'French Southern Territories', 'code' => 'TF', 'flag' => '', 'phone_code' => '+262'],
            ['name' => 'Gabon', 'code' => 'GAB', 'flag' => '🇬🇦', 'phone_code' => '+241'],
            ['name' => 'Gambia', 'code' => 'GMB', 'flag' => '🇬🇲', 'phone_code' => '+220'],
            ['name' => 'Georgia', 'code' => 'GEO', 'flag' => '🇬🇪', 'phone_code' => '+995'],
            ['name' => 'Germany', 'code' => 'DEU', 'flag' => '🇩🇪', 'phone_code' => '+49'],
            ['name' => 'Ghana', 'code' => 'GHA', 'flag' => '🇬🇭', 'phone_code' => '+233'],
            ['name' => 'Gibraltar', 'code' => 'GIB', 'flag' => '🇬🇮', 'phone_code' => '+350'],
            ['name' => 'Greece', 'code' => 'GRC', 'flag' => '🇬🇷', 'phone_code' => '+30'],
            ['name' => 'Greenland', 'code' => 'GRL', 'flag' => '🇬🇱', 'phone_code' => '+299'],
            ['name' => 'Grenada', 'code' => 'GRD', 'flag' => '🇬🇩', 'phone_code' => '+1473'],
            ['name' => 'Guadeloupe', 'code' => 'GLP', 'flag' => '🇬🇵', 'phone_code' => '+590'],
            ['name' => 'Guam', 'code' => 'GUM', 'flag' => '🇬🇺', 'phone_code' => '+1671'],
            ['name' => 'Guatemala', 'code' => 'GTM', 'flag' => '🇬🇹', 'phone_code' => '+502'],
            ['name' => 'Guinea', 'code' => 'GIN', 'flag' => '🇬🇳', 'phone_code' => '+224'],
            ['name' => 'Guinea-Bissau', 'code' => 'GNB', 'flag' => '🇬🇼', 'phone_code' => '+245'],
            ['name' => 'Guyana', 'code' => 'GUY', 'flag' => '🇬🇾', 'phone_code' => '+592'],
            ['name' => 'Haiti', 'code' => 'HTI', 'flag' => '🇭🇹', 'phone_code' => '+509'],
            ['name' => 'Heard Island and Mcdonald Islands', 'code' => 'HM', 'flag' => '', 'phone_code' => '+672'],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VAT', 'flag' => '🇻🇦', 'phone_code' => '+39'],
            ['name' => 'Honduras', 'code' => 'HND', 'flag' => '🇭🇳', 'phone_code' => '+504'],
            ['name' => 'Hong Kong', 'code' => 'HKG', 'flag' => '🇭🇰', 'phone_code' => '+852'],
            ['name' => 'Hungary', 'code' => 'HUN', 'flag' => '🇭🇺', 'phone_code' => '+36'],
            ['name' => 'Iceland', 'code' => 'ISL', 'flag' => '🇮🇸', 'phone_code' => '+354'],
            ['name' => 'India', 'code' => 'IND', 'flag' => '🇮🇳', 'phone_code' => '+91'],
            ['name' => 'Indonesia', 'code' => 'IDN', 'flag' => '🇮🇩', 'phone_code' => '+62'],
            ['name' => 'Iran, Islamic Republic of', 'code' => 'IRN', 'flag' => '🇮🇷', 'phone_code' => '+98'],
            ['name' => 'Iraq', 'code' => 'IRQ', 'flag' => '🇮🇶', 'phone_code' => '+964'],
            ['name' => 'Ireland', 'code' => 'IRL', 'flag' => '🇮🇪', 'phone_code' => '+353'],
            ['name' => 'Israel', 'code' => 'ISR', 'flag' => '🇮🇱', 'phone_code' => '+972'],
            ['name' => 'Italy', 'code' => 'ITA', 'flag' => '🇮🇹', 'phone_code' => '+39'],
            ['name' => 'Jamaica', 'code' => 'JAM', 'flag' => '🇯🇲', 'phone_code' => '+1876'],
            ['name' => 'Japan', 'code' => 'JPN', 'flag' => '🇯🇵', 'phone_code' => '+81'],
            ['name' => 'Jordan', 'code' => 'JOR', 'flag' => '🇯🇴', 'phone_code' => '+962'],
            ['name' => 'Kazakhstan', 'code' => 'KAZ', 'flag' => '🇰🇿', 'phone_code' => '+7'],
            ['name' => 'Kenya', 'code' => 'KEN', 'flag' => '🇰🇪', 'phone_code' => '+254'],
            ['name' => 'Kiribati', 'code' => 'KIR', 'flag' => '🇰🇮', 'phone_code' => '+686'],
            ['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'PRK', 'flag' => '🇰🇵', 'phone_code' => '+850'],
            ['name' => 'Korea, Republic of', 'code' => 'KOR', 'flag' => '🇰🇷', 'phone_code' => '+82'],
            ['name' => 'Kuwait', 'code' => 'KWT', 'flag' => '🇰🇼', 'phone_code' => '+965'],
            ['name' => 'Kyrgyzstan', 'code' => 'KGZ', 'flag' => '🇰🇬', 'phone_code' => '+996'],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LAO', 'flag' => '🇱🇦', 'phone_code' => '+856'],
            ['name' => 'Latvia', 'code' => 'LVA', 'flag' => '🇱🇻', 'phone_code' => '+371'],
            ['name' => 'Lebanon', 'code' => 'LBN', 'flag' => '🇱🇧', 'phone_code' => '+961'],
            ['name' => 'Lesotho', 'code' => 'LSO', 'flag' => '🇱🇸', 'phone_code' => '+266'],
            ['name' => 'Liberia', 'code' => 'LBR', 'flag' => '🇱🇷', 'phone_code' => '+231'],
            ['name' => 'Libyan Arab Jamahiriya', 'code' => 'LBY', 'flag' => '🇱🇾', 'phone_code' => '+218'],
            ['name' => 'Liechtenstein', 'code' => 'LIE', 'flag' => '🇱🇮', 'phone_code' => '+423'],
            ['name' => 'Lithuania', 'code' => 'LTU', 'flag' => '🇱🇹', 'phone_code' => '+370'],
            ['name' => 'Luxembourg', 'code' => 'LUX', 'flag' => '🇱🇺', 'phone_code' => '+352'],
            ['name' => 'Macao', 'code' => 'MAC', 'flag' => '🇲🇴', 'phone_code' => '+853'],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MKD', 'flag' => '🇲🇰', 'phone_code' => '+389'],
            ['name' => 'Madagascar', 'code' => 'MDG', 'flag' => '🇲🇬', 'phone_code' => '+261'],
            ['name' => 'Malawi', 'code' => 'MWI', 'flag' => '🇲🇼', 'phone_code' => '+265'],
            ['name' => 'Malaysia', 'code' => 'MYS', 'flag' => '🇲🇾', 'phone_code' => '+60'],
            ['name' => 'Maldives', 'code' => 'MDV', 'flag' => '🇲🇻', 'phone_code' => '+960'],
            ['name' => 'Mali', 'code' => 'MLI', 'flag' => '🇲🇱', 'phone_code' => '+223'],
            ['name' => 'Malta', 'code' => 'MLT', 'flag' => '🇲🇹', 'phone_code' => '+356'],
            ['name' => 'Marshall Islands', 'code' => 'MHL', 'flag' => '🇲🇭', 'phone_code' => '+692'],
            ['name' => 'Martinique', 'code' => 'MTQ', 'flag' => '🇲🇶', 'phone_code' => '+596'],
            ['name' => 'Mauritania', 'code' => 'MRT', 'flag' => '🇲🇷', 'phone_code' => '+222'],
            ['name' => 'Mauritius', 'code' => 'MUS', 'flag' => '🇲🇺', 'phone_code' => '+230'],
            ['name' => 'Mayotte', 'code' => 'YT', 'flag' => '', 'phone_code' => '+269'],
            ['name' => 'Mexico', 'code' => 'MEX', 'flag' => '🇲🇽', 'phone_code' => '+52'],
            ['name' => 'Micronesia, Federated States of', 'code' => 'FSM', 'flag' => '🇫🇲', 'phone_code' => '+691'],
            ['name' => 'Moldova, Republic of', 'code' => 'MDA', 'flag' => '🇲🇩', 'phone_code' => '+373'],
            ['name' => 'Monaco', 'code' => 'MCO', 'flag' => '🇲🇨', 'phone_code' => '+377'],
            ['name' => 'Mongolia', 'code' => 'MNG', 'flag' => '🇲🇳', 'phone_code' => '+976'],
            ['name' => 'Montserrat', 'code' => 'MSR', 'flag' => '🇲🇸', 'phone_code' => '+1664'],
            ['name' => 'Morocco', 'code' => 'MAR', 'flag' => '🇲🇦', 'phone_code' => '+212'],
            ['name' => 'Mozambique', 'code' => 'MOZ', 'flag' => '🇲🇿', 'phone_code' => '+258'],
            ['name' => 'Myanmar', 'code' => 'MMR', 'flag' => '🇲🇲', 'phone_code' => '+95'],
            ['name' => 'Namibia', 'code' => 'NAM', 'flag' => '🇳🇦', 'phone_code' => '+264'],
            ['name' => 'Nauru', 'code' => 'NRU', 'flag' => '🇳🇷', 'phone_code' => '+674'],
            ['name' => 'Nepal', 'code' => 'NPL', 'flag' => '🇳🇵', 'phone_code' => '+977'],
            ['name' => 'Netherlands', 'code' => 'NLD', 'flag' => '🇳🇱', 'phone_code' => '+31'],
            ['name' => 'Netherlands Antilles', 'code' => 'ANT', 'flag' => '', 'phone_code' => '+599'],
            ['name' => 'New Caledonia', 'code' => 'NCL', 'flag' => '🇳🇨', 'phone_code' => '+687'],
            ['name' => 'New Zealand', 'code' => 'NZL', 'flag' => '🇳🇿', 'phone_code' => '+64'],
            ['name' => 'Nicaragua', 'code' => 'NIC', 'flag' => '🇳🇮', 'phone_code' => '+505'],
            ['name' => 'Niger', 'code' => 'NER', 'flag' => '🇳🇪', 'phone_code' => '+227'],
            ['name' => 'Nigeria', 'code' => 'NGA', 'flag' => '🇳🇬', 'phone_code' => '+234'],
            ['name' => 'Niue', 'code' => 'NIU', 'flag' => '🇳🇺', 'phone_code' => '+683'],
            ['name' => 'Norfolk Island', 'code' => 'NFK', 'flag' => '🇳🇫', 'phone_code' => '+672'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MNP', 'flag' => '🇲🇵', 'phone_code' => '+1670'],
            ['name' => 'Norway', 'code' => 'NOR', 'flag' => '🇳🇴', 'phone_code' => '+47'],
            ['name' => 'Oman', 'code' => 'OMN', 'flag' => '🇴🇲', 'phone_code' => '+968'],
            ['name' => 'Pakistan', 'code' => 'PAK', 'flag' => '🇵🇰', 'phone_code' => '+92'],
            ['name' => 'Palau', 'code' => 'PLW', 'flag' => '🇵🇼', 'phone_code' => '+680'],
            ['name' => 'Palestinian Territory, Occupied', 'code' => 'PS', 'flag' => '', 'phone_code' => '+970'],
            ['name' => 'Panama', 'code' => 'PAN', 'flag' => '🇵🇦', 'phone_code' => '+507'],
            ['name' => 'Papua New Guinea', 'code' => 'PNG', 'flag' => '🇵🇬', 'phone_code' => '+675'],
            ['name' => 'Paraguay', 'code' => 'PRY', 'flag' => '🇵🇾', 'phone_code' => '+595'],
            ['name' => 'Peru', 'code' => 'PER', 'flag' => '🇵🇪', 'phone_code' => '+51'],
            ['name' => 'Philippines', 'code' => 'PHL', 'flag' => '🇵🇭', 'phone_code' => '+63'],
            ['name' => 'Pitcairn', 'code' => 'PCN', 'flag' => '🇵🇳', 'phone_code' => '+872'],
            ['name' => 'Poland', 'code' => 'POL', 'flag' => '🇵🇱', 'phone_code' => '+48'],
            ['name' => 'Portugal', 'code' => 'PRT', 'flag' => '🇵🇹', 'phone_code' => '+351'],
            ['name' => 'Puerto Rico', 'code' => 'PRI', 'flag' => '🇵🇷', 'phone_code' => '+1787'],
            ['name' => 'Qatar', 'code' => 'QAT', 'flag' => '🇶🇦', 'phone_code' => '+974'],
            ['name' => 'Reunion', 'code' => 'REU', 'flag' => '🇷🇪', 'phone_code' => '+262'],
            ['name' => 'Romania', 'code' => 'ROM', 'flag' => '🇷🇴', 'phone_code' => '+40'],
            ['name' => 'Russian Federation', 'code' => 'RUS', 'flag' => '🇷🇺', 'phone_code' => '+7'],
            ['name' => 'Rwanda', 'code' => 'RWA', 'flag' => '🇷🇼', 'phone_code' => '+250'],
            ['name' => 'Saint Helena', 'code' => 'SHN', 'flag' => '🇸🇭', 'phone_code' => '+290'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KNA', 'flag' => '🇰🇳', 'phone_code' => '+1869'],
            ['name' => 'Saint Lucia', 'code' => 'LCA', 'flag' => '🇱🇨', 'phone_code' => '+1758'],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'SPM', 'flag' => '🇵🇲', 'phone_code' => '+508'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VCT', 'flag' => '🇻🇨', 'phone_code' => '+1784'],
            ['name' => 'Samoa', 'code' => 'WSM', 'flag' => '🇼🇸', 'phone_code' => '+685'],
            ['name' => 'San Marino', 'code' => 'SMR', 'flag' => '🇸🇲', 'phone_code' => '+378'],
            ['name' => 'Sao Tome and Principe', 'code' => 'STP', 'flag' => '🇸🇹', 'phone_code' => '+239'],
            ['name' => 'Saudi Arabia', 'code' => 'SAU', 'flag' => '🇸🇦', 'phone_code' => '+966'],
            ['name' => 'Senegal', 'code' => 'SEN', 'flag' => '🇸🇳', 'phone_code' => '+221'],
            ['name' => 'Serbia and Montenegro', 'code' => 'CS', 'flag' => '', 'phone_code' => '+381'],
            ['name' => 'Seychelles', 'code' => 'SYC', 'flag' => '🇸🇨', 'phone_code' => '+248'],
            ['name' => 'Sierra Leone', 'code' => 'SLE', 'flag' => '🇸🇱', 'phone_code' => '+232'],
            ['name' => 'Singapore', 'code' => 'SGP', 'flag' => '🇸🇬', 'phone_code' => '+65'],
            ['name' => 'Slovakia', 'code' => 'SVK', 'flag' => '🇸🇰', 'phone_code' => '+421'],
            ['name' => 'Slovenia', 'code' => 'SVN', 'flag' => '🇸🇮', 'phone_code' => '+386'],
            ['name' => 'Solomon Islands', 'code' => 'SLB', 'flag' => '🇸🇧', 'phone_code' => '+677'],
            ['name' => 'Somalia', 'code' => 'SOM', 'flag' => '🇸🇴', 'phone_code' => '+252'],
            ['name' => 'South Africa', 'code' => 'ZAF', 'flag' => '🇿🇦', 'phone_code' => '+27'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'flag' => '', 'phone_code' => '+500'],
            ['name' => 'Spain', 'code' => 'ESP', 'flag' => '🇪🇸', 'phone_code' => '+34'],
            ['name' => 'Sri Lanka', 'code' => 'LKA', 'flag' => '🇱🇰', 'phone_code' => '+94'],
            ['name' => 'Sudan', 'code' => 'SDN', 'flag' => '🇸🇩', 'phone_code' => '+249'],
            ['name' => 'Suriname', 'code' => 'SUR', 'flag' => '🇸🇷', 'phone_code' => '+597'],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJM', 'flag' => '🇸🇯', 'phone_code' => '+47'],
            ['name' => 'Swaziland', 'code' => 'SWZ', 'flag' => '🇸🇿', 'phone_code' => '+268'],
            ['name' => 'Sweden', 'code' => 'SWE', 'flag' => '🇸🇪', 'phone_code' => '+46'],
            ['name' => 'Switzerland', 'code' => 'CHE', 'flag' => '🇨🇭', 'phone_code' => '+41'],
            ['name' => 'Syrian Arab Republic', 'code' => 'SYR', 'flag' => '🇸🇾', 'phone_code' => '+963'],
            ['name' => 'Taiwan, Province of China', 'code' => 'TWN', 'flag' => '🇹🇼', 'phone_code' => '+886'],
            ['name' => 'Tajikistan', 'code' => 'TJK', 'flag' => '🇹🇯', 'phone_code' => '+992'],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZA', 'flag' => '🇹🇿', 'phone_code' => '+255'],
            ['name' => 'Thailand', 'code' => 'THA', 'flag' => '🇹🇭', 'phone_code' => '+66'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'flag' => '', 'phone_code' => '+670'],
            ['name' => 'Togo', 'code' => 'TGO', 'flag' => '🇹🇬', 'phone_code' => '+228'],
            ['name' => 'Tokelau', 'code' => 'TKL', 'flag' => '🇹🇰', 'phone_code' => '+690'],
            ['name' => 'Tonga', 'code' => 'TON', 'flag' => '🇹🇴', 'phone_code' => '+676'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TTO', 'flag' => '🇹🇹', 'phone_code' => '+1868'],
            ['name' => 'Tunisia', 'code' => 'TUN', 'flag' => '🇹🇳', 'phone_code' => '+216'],
            ['name' => 'Turkey', 'code' => 'TUR', 'flag' => '🇹🇷', 'phone_code' => '+90'],
            ['name' => 'Turkmenistan', 'code' => 'TKM', 'flag' => '🇹🇲', 'phone_code' => '+993'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TCA', 'flag' => '🇹🇨', 'phone_code' => '+1649'],
            ['name' => 'Tuvalu', 'code' => 'TUV', 'flag' => '🇹🇻', 'phone_code' => '+688'],
            ['name' => 'Uganda', 'code' => 'UGA', 'flag' => '🇺🇬', 'phone_code' => '+256'],
            ['name' => 'Ukraine', 'code' => 'UKR', 'flag' => '🇺🇦', 'phone_code' => '+380'],
            ['name' => 'United Arab Emirates', 'code' => 'ARE', 'flag' => '🇦🇪', 'phone_code' => '+971'],
            ['name' => 'United Kingdom', 'code' => 'GBR', 'flag' => '🇬🇧', 'phone_code' => '+44'],
            ['name' => 'United States', 'code' => 'USA', 'flag' => '🇺🇸', 'phone_code' => '+1'],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'flag' => '', 'phone_code' => '+1'],
            ['name' => 'Uruguay', 'code' => 'URY', 'flag' => '🇺🇾', 'phone_code' => '+598'],
            ['name' => 'Uzbekistan', 'code' => 'UZB', 'flag' => '🇺🇿', 'phone_code' => '+998'],
            ['name' => 'Vanuatu', 'code' => 'VUT', 'flag' => '🇻🇺', 'phone_code' => '+678'],
            ['name' => 'Venezuela', 'code' => 'VEN', 'flag' => '🇻🇪', 'phone_code' => '+58'],
            ['name' => 'Viet Nam', 'code' => 'VNM', 'flag' => '🇻🇳', 'phone_code' => '+84'],
            ['name' => 'Virgin Islands, British', 'code' => 'VGB', 'flag' => '🇻🇬', 'phone_code' => '+1284'],
            ['name' => 'Virgin Islands, U.s.', 'code' => 'VIR', 'flag' => '🇻🇮', 'phone_code' => '+1340'],
            ['name' => 'Wallis and Futuna', 'code' => 'WLF', 'flag' => '🇼🇫', 'phone_code' => '+681'],
            ['name' => 'Western Sahara', 'code' => 'ESH', 'flag' => '🇪🇭', 'phone_code' => '+212'],
            ['name' => 'Yemen', 'code' => 'YEM', 'flag' => '🇾🇪', 'phone_code' => '+967'],
            ['name' => 'Zambia', 'code' => 'ZMB', 'flag' => '🇿🇲', 'phone_code' => '+260'],
            ['name' => 'Zimbabwe', 'code' => 'ZWE', 'flag' => '🇿🇼', 'phone_code' => '+263'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
